[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 1

[[main]]
  identifier = "neovim"
  name =  "Neovim"
  url = "posts/neovim"
  weight = 2

[[main]]
  identifier = "stenography"
  name =  "Stenography"
  url = "posts/stenography"
  weight = 2
