services:
  # Deployed website
  hugo:
    image: jakejarvis/hugo-extended:latest
    restart: unless-stopped
    ports:
      - 1313:1313
    volumes:
      - ./:/src
    command: server --baseURL=dereklomax.com --buildFuture --bind 0.0.0.0 --appendPort=false

  # Easy development with docker or podman
  # Default file watching does not work with containers, use the --poll option for easy hot reload
  development:
    image: jakejarvis/hugo-extended:latest
    restart: unless-stopped
    ports:
      - 1313:1313
    volumes:
      - ./:/src
    command: server --buildDrafts --buildFuture --bind 0.0.0.0 --poll 700ms
